version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kriswoodworking-site:latest
    container_name: kriswoodworking-git
    volumes:
      - ./:/portainer/Files/AppData/Config/Nginx/www:ro
    ports:
      - "6689:80"
    restart: unless-stopped

